import { mkdir, readdir, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';

export interface SmoldevGenerateInput {
  readonly spec: string;
  readonly outputDir: string;
  readonly stack?: string;
}

export interface SmoldevGenerationPlan {
  readonly language: 'zh' | 'en';
  readonly projectName: string;
  readonly normalizedSpec: string;
  readonly stack: string;
  readonly planYaml: string;
}

export interface SmoldevFileSpec {
  readonly path: string;
  readonly purpose: string;
  readonly content: string;
}

export interface SmoldevProgress {
  readonly current: number;
  readonly total: number;
  readonly file: string;
}

export interface SmoldevGenerateResult {
  readonly outputDir: string;
  readonly plan: SmoldevGenerationPlan;
  readonly files: readonly SmoldevFileSpec[];
  readonly filesCreated: readonly string[];
  readonly progress: readonly SmoldevProgress[];
}

function detectLanguage(spec: string): 'zh' | 'en' {
  return /[\u3400-\u9fff]/.test(spec) ? 'zh' : 'en';
}

function toProjectName(spec: string): string {
  const fallback = 'smoldev-app';
  const slug = spec
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, ' ')
    .trim()
    .split(/\s+/)
    .slice(0, 4)
    .join('-')
    .replace(/-+/g, '-');
  return slug.length > 0 ? slug : fallback;
}

function toYaml(plan: {
  readonly language: 'zh' | 'en';
  readonly projectName: string;
  readonly stack: string;
  readonly normalizedSpec: string;
  readonly files: readonly SmoldevFileSpec[];
}): string {
  return [
    'version: 1',
    `language: ${plan.language}`,
    `project_name: ${plan.projectName}`,
    `stack: ${JSON.stringify(plan.stack)}`,
    'spec: |',
    ...plan.normalizedSpec.split('\n').map((line) => `  ${line}`),
    'files:',
    ...plan.files.map((file) => `  - path: ${JSON.stringify(file.path)}\n    purpose: ${JSON.stringify(file.purpose)}`),
  ].join('\n');
}

function renderReadme(plan: {
  readonly language: 'zh' | 'en';
  readonly projectName: string;
  readonly normalizedSpec: string;
  readonly stack: string;
}): string {
  const title = plan.projectName;
  const description =
    plan.language === 'zh'
      ? `该项目由 smoldev_generate 自动生成。\n\n需求说明：${plan.normalizedSpec}`
      : `This project was generated by smoldev_generate.\n\nSpec: ${plan.normalizedSpec}`;
  return [
    `# ${title}`,
    '',
    description,
    '',
    '## Stack',
    plan.stack,
    '',
    '## Scripts',
    '- `pnpm build`',
    '- `pnpm test`',
  ].join('\n');
}

function renderPackageJson(plan: {
  readonly projectName: string;
  readonly stack: string;
  readonly hasReact: boolean;
}): string {
  const pkg = {
    name: plan.projectName,
    version: '0.1.0',
    private: true,
    type: 'module',
    scripts: {
      build: 'tsc --noEmit',
      test: 'node --eval "console.log(\'no tests yet\')"',
      start: plan.hasReact ? 'echo "use your preferred bundler"' : 'node src/index.ts',
    },
    metadata: {
      generatedBy: 'smoldev_generate',
      stack: plan.stack,
    },
  };
  return `${JSON.stringify(pkg, null, 2)}\n`;
}

function renderTsConfig(): string {
  return `${JSON.stringify(
    {
      compilerOptions: {
        target: 'ES2022',
        module: 'ESNext',
        moduleResolution: 'bundler',
        strict: true,
        noUncheckedIndexedAccess: true,
        skipLibCheck: true,
      },
      include: ['src/**/*'],
    },
    null,
    2,
  )}\n`;
}

function renderNodeEntry(plan: {
  readonly language: 'zh' | 'en';
  readonly normalizedSpec: string;
}): string {
  const line =
    plan.language === 'zh'
      ? `console.log('smol-dev 启动：${plan.normalizedSpec.replace(/'/g, '')}');`
      : `console.log('smol-dev bootstrap: ${plan.normalizedSpec.replace(/'/g, '')}');`;
  return [
    'export function main(): void {',
    `  ${line}`,
    '}',
    '',
    'main();',
    '',
  ].join('\n');
}

function renderReactEntry(plan: {
  readonly language: 'zh' | 'en';
  readonly normalizedSpec: string;
}): string {
  const heading = plan.language === 'zh' ? '生成的 React 页面' : 'Generated React page';
  return [
    "import React from 'react';",
    '',
    'export function App(): React.JSX.Element {',
    '  return (',
    "    <main>",
    `      <h1>${heading}</h1>`,
    `      <p>${plan.normalizedSpec.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</p>`,
    '    </main>',
    '  );',
    '}',
    '',
  ].join('\n');
}

function buildFileSpecs(plan: {
  readonly language: 'zh' | 'en';
  readonly projectName: string;
  readonly normalizedSpec: string;
  readonly stack: string;
}): readonly SmoldevFileSpec[] {
  const lowerStack = plan.stack.toLowerCase();
  const hasReact = lowerStack.includes('react');
  const hasExpress = lowerStack.includes('express') || lowerStack.includes('node');

  const files: SmoldevFileSpec[] = [
    {
      path: 'README.md',
      purpose: 'project overview',
      content: renderReadme(plan),
    },
    {
      path: 'package.json',
      purpose: 'package metadata and scripts',
      content: renderPackageJson({
        projectName: plan.projectName,
        stack: plan.stack,
        hasReact,
      }),
    },
    {
      path: 'tsconfig.json',
      purpose: 'typescript compiler setup',
      content: renderTsConfig(),
    },
  ];

  if (hasReact) {
    files.push(
      {
        path: 'src/App.tsx',
        purpose: 'react root component',
        content: renderReactEntry(plan),
      },
      {
        path: 'src/main.tsx',
        purpose: 'react bootstrap entry',
        content: [
          "import { App } from './App';",
          '',
          "console.log('Render App', App.name);",
          '',
        ].join('\n'),
      },
    );
  } else {
    files.push({
      path: 'src/index.ts',
      purpose: 'node entrypoint',
      content: renderNodeEntry(plan),
    });
  }

  if (hasExpress) {
    files.push({
      path: 'src/server.ts',
      purpose: 'http server skeleton',
      content: [
        "import { createServer } from 'node:http';",
        '',
        'const server = createServer((_req, res) => {',
        "  res.writeHead(200, { 'content-type': 'application/json' });",
        "  res.end(JSON.stringify({ ok: true }));",
        '});',
        '',
        'if (process.env.NODE_ENV !== \"test\") {',
        '  server.listen(3000);',
        '}',
        '',
      ].join('\n'),
    });
  }

  return files;
}

async function ensureOutputDirIsSafe(outputDir: string): Promise<void> {
  try {
    const info = await stat(outputDir);
    if (!info.isDirectory()) {
      throw new Error(`outputDir is not a directory: ${outputDir}`);
    }

    const entries = await readdir(outputDir);
    if (entries.length > 0) {
      throw new Error(`outputDir must be empty: ${outputDir}`);
    }
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    if (message.includes('ENOENT')) {
      await mkdir(outputDir, { recursive: true });
      return;
    }
    throw error;
  }
}

async function writeSpecFile(
  outputDir: string,
  file: SmoldevFileSpec,
  current: number,
  total: number,
): Promise<SmoldevProgress> {
  const target = path.join(outputDir, file.path);
  await mkdir(path.dirname(target), { recursive: true });
  await writeFile(target, file.content, 'utf8');
  return {
    current,
    total,
    file: file.path,
  };
}

export async function smoldevGenerate(input: SmoldevGenerateInput): Promise<SmoldevGenerateResult> {
  const normalizedSpec = input.spec.trim();
  if (!normalizedSpec) {
    throw new Error('spec is required');
  }

  const normalizedOutputDir = path.resolve(input.outputDir);
  await ensureOutputDirIsSafe(normalizedOutputDir);

  const stack = input.stack?.trim() || 'node+typescript';
  const language = detectLanguage(normalizedSpec);
  const projectName = toProjectName(normalizedSpec);

  const draftPlan = {
    language,
    projectName,
    normalizedSpec,
    stack,
  } as const;
  const files = buildFileSpecs(draftPlan);
  const plan: SmoldevGenerationPlan = {
    ...draftPlan,
    planYaml: toYaml({
      ...draftPlan,
      files,
    }),
  };

  const progress = await Promise.all(
    files.map((file, index) => writeSpecFile(normalizedOutputDir, file, index + 1, files.length)),
  );

  return {
    outputDir: normalizedOutputDir,
    plan,
    files,
    filesCreated: files.map((item) => item.path),
    progress,
  };
}
